In [2]:
list = range(2000000)

In [3]:
%time for n in range(1,10): r=[num*5 for num in list]

Wall time: 3.37 s


In [4]:
import numpy as zz

In [5]:
list2 = zz.arange(2000000)

In [6]:
%time for n in range(1,10): r = list2 * 5

Wall time: 173 ms


In [7]:
a = zz.zeros(14)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
type(a[0])

numpy.float64

In [9]:
b= zz.ones(5)

In [10]:
b

array([1., 1., 1., 1., 1.])

In [11]:
c = zz.empty(10)
c

array([3.22646744e-307, 2.33645657e-307, 1.33511901e-307, 2.11392372e-307,
       1.60216183e-306, 7.56602523e-307, 1.11258446e-306, 4.45063578e-308,
       1.22383816e-307, 1.37959129e-306])